### PR TITLE
Stage 1 1 markup

### PR DESCRIPTION
**Pull request by IMLUOAI**
Frontend markup, api, auth, and thirdPartyAPI.

### CODE REVIEW

**Comment by IMLUOAI** [comment]
In this project, I have tried my best to code up the markup and api on my own. Based on the UI design from Figma, I have  nested the Preloader, newsSection, and About section in the Main.jsx, and I was still a little bit confused with the logic among the navigation of the About and Main. Do we need to click on a button to nav to the About or Main section? or just need to scroll the mouth to nav to each of the subSection in the Main? In my code, I wrote the About part into hardcoded way since I thought it doesn't need to be changed by various users in reality.

**Comment by ImaliaNsk** [comment]
Hey! Thanks for sending your code for review! The project looks good in general, but will need some refactoring. Please find the list below. Also, remember that you can reach out to your tutor with any question you have anout this project. Good luck! 

# Summary:
### Performance Criteria

- [ ]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout and get out of the grid in the layout.

* Content of the page should be centered horizontally: https://prnt.sc/0syk8iEuzSsM
* Header background image should be only in header.
* Text in "Search" button should be white
* Please note how the active link in the navigation should be indicated, according to the design: https://prnt.sc/IabLzmndXBGE The underline of the link should be exactly on the border of the header navigation.
* https://prnt.sc/_kR29-xRGvh0 Navigation is broken when logged in
* https://prnt.sc/I8iJJI_aRYWG Nothing found and preloader are shown at the same time, with flag "hasSearched"
* https://prnt.sc/7sdd6fBJ83Wl Saved-news page doesn't match the design
* https://prnt.sc/Rann4uXLdj35 Popup layout looks different from the design
* Links in the footer shouldn't be underlined

- [ ]  The project is adapted for different screen resolutions and looks correctly on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.

* The project isn't adapted to tablets and mobiles, both pages scroll on all screens from 1464px and down

- [ ]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.

* Please add some sample cards to both pages so that I can check the layout. Since the search isn't working yet (there's a console error when trying to search), you can just hard-code them.
* Links should be opening in new tabs

- [ ]  Classes are named according to BEM specifications.

* https://prnt.sc/NmmVYjvjAGhH Elements shouldn't be outside of the block. Please correct all similar issues
* Elements with the same role and styles should have the same element class (links in the header, footer). You can use a modifier to assign unique styles (e.g. underlining for the active link)

- [ ]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g. a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.

* Content in "about" section isn't a single paragraph, it needs a different semantic structure. You can use a number of paragraphs, or a list.

- [x]  The correct approach is chosen for positioning elements, and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid`  layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [ ]  Your project contains:
  - [x] An `images`
  - [ ] A `components` folder with JS and CSS files for the components.
  * CSS files are stored separately.
  - [x] A `fonts` folder.
- [x]  There are no linting errors or warnings.

### Best Practices

- [ ]  Buttons, input fields, and links are implemented in all of the states specified in the design.

* Hover and active effects of the search button doesn't match the design

- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [ ]  The icons are exported in SVG format.
- [ ]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.

### Recommendations

- [x]  System fonts are connected as alternatives to each of your fonts.
- [x]  Images have an `alt` attribute containing appropriate values.
- [ ]  Raster and vector images have been optimized.

## Number of points: 41

**Comment by ImaliaNsk** [comment]
Thank you for the corrections! They look pretty good, and the project looks better in general. However, it requires some further fixing. Please find comments below.

# Summary:
### Performance Criteria

- [ ]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout and get out of the grid in the layout.

* Content of the page should be centered horizontally: https://prnt.sc/0syk8iEuzSsM
* https://prnt.sc/icLZ1aEnV3qf Saved-news page doesn't match the design
* Please add some sample cards to saved-articles page so that I can check the layout
* https://prnt.sc/7MsUkVYXKbBU Preloader position is incorrect, please check the design
* https://prnt.sc/JCVYZs-PzhBG "Nothing found" layout doesn't match the design


* https://prnt.sc/I8iJJI_aRYWG Nothing found and preloader are shown at the same time, with flag "hasSearched"

* https://prnt.sc/Rann4uXLdj35 Popup layout looks different from the design
* Links in the footer shouldn't be underlined

- [ ]  The project is adapted for different screen resolutions and looks correctly on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.

* The project isn't adapted to tablets and mobiles, both pages scroll on all screens from 1464px and down

- [ ]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.

* Please add some sample cards to both pages so that I can check the layout.
* Links should be opening in new tabs

- [ ]  Classes are named according to BEM specifications.

* https://prnt.sc/NmmVYjvjAGhH Elements shouldn't be outside of the block. Please correct all similar issues
* Elements with the same role and styles should have the same element class (links in the header, footer). You can use a modifier to assign unique styles (e.g. underlining for the active link)

- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g. a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
- [x]  The correct approach is chosen for positioning elements, and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid`  layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.
  - [x] A `fonts` folder.
- [x]  There are no linting errors or warnings.

### Best Practices

- [ ]  Buttons, input fields, and links are implemented in all of the states specified in the design.

* Hover and active effects of the search button doesn't match the design

- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.

### Recommendations

- [x]  System fonts are connected as alternatives to each of your fonts.
- [x]  Images have an `alt` attribute containing appropriate values.
- [ ]  Raster and vector images have been optimized.

* Main background image shouldn't be in svg, please use raster graphics format for pictures like this (jpg or png).

## Number of points: 54

**Comment by IMLUOAI** [comment]
Hi, ImaliNSK! Tks for taking the time to comment on my code. Did you really review the latest commit of my code? I felt like some comments you mentioned above weren't quite true. For example, my current code has the sample cards on the search page, the links are clickable and also able to open in a new tab, and the entire code now has the responsive resolution set up for iPhone and tablet as well. Plus, the successful signup modal looks pretty well on my computer, and the footlinks only show their underlines after hovering over them.

**Pull request merged**
